version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: lms-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: lmsfilmes
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - lms-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: lms-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - lms-network

  lms-app:
    build: .
    container_name: lms-films-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: lmsfilmes
      MONGO_USER: admin
      MONGO_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - lms-network

volumes:
  mongodb_data:

networks:
  lms-network:
    driver: bridge
