spring:
  application:
    name: "LMS Filmes"

  cache:
    type: redis

  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      url: ${REDIS_URL}

  rabbitmq:
    addresses: ${RABBITMQ_URL}

jwt:
  auth:
    secret: "${JWT_SECRET}"
    expiration: ${JWT_EXPIRATION}

tmdb:
  api:
    url: "${TMDB_API_URL}"
    key: "${TMDB_API_KEY}"

logging:
  level:
    org:
      springframework:
        cache: DEBUG
        data:
          mongodb: DEBUG
          redis: DEBUG
